let body=d3.select("body");
let svg= body.append("svg").attr('width',"500")
                   .attr('height',"500")
                   .attr("stroke",'blue')
                   .style('border','5px solid red')
                   .attr("fill","orange")

svg.append("text")
          .attr('x',"10")
          .attr('y',"40")
          .attr('font-size',"20px")
          .text("Good Morning Friends")
          svg.append("text")
          .attr('x',"10")
          .attr('y',"100")
          .attr('font-size',"90px")
          .text("Good Morning Friends")
          svg.append("text")
          .attr('x',"10")
          .attr('y',"160")
          .attr('font-size',"20px")
          .text("Good Morning Friends")
          svg.append("text")
          .attr('x',"10")
          .attr('y',"200")
          .attr('font-size',"90px")
          .text("Good Morning Friends")
         
          